<SignButton>
    font_name: "LuckiestGuy"
    font_size: "80sp"
    background_color: 1,1,1,0
    on_release: app.select_sign(self.text)
    canvas.before:
        Color:
            rgb: root.bg_color
        RoundedRectangle:
            size: self.size
            pos: self.x,self.y+5
            radius: [10]



MDScreen:
    name: "select_sign"
    MDFloatLayout:
        md_bg_color: rgba(60,12,156,255)
        MDLabel:
            text:"Select\nSign"
            font_name:"LuckiestGuy"
            font_size:"55sp"
            halign:"center"
            pos_hint:{"center_x": .5, "center_y": .8}
            color: 1,1,1,1
            line_height: 1.1
        MDGridLayout:
            rows: 2
            cols: 2
            size_hint: .6,.3
            pos_hint:{"center_x": .5, "center_y": .47}
            spacing: 15
            SignButton:
                text: "+"
                bg_color: 40/255, 6/255, 109/255, 1
            SignButton:
                text: "-"
                bg_color: 87/255, 23/255, 216/255, 1
            SignButton:
                text: "×"
                bg_color: 87/255, 23/255, 216/255, 1
            SignButton:
                text: "÷"
                bg_color: 40/255, 6/255, 109/255, 1


        Button:
            text: "Back"
            font_name: "LuckiestGuy"
            font_size: "40sp"
            size_hint: .55,.12
            pos_hint: {"center_x": .5 ,"center_y": .15}
            background_color:1,1,1,0
            on_release:
                root.manager.current="start"
            canvas.before:
                Color:
                    rgb: rgba(251,187,29,255)
                RoundedRectangle:
                    size: self.size
                    pos: self.x, self.y+5
                    radius: [10]